name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run hello.py
        run: python hello.py

      - name: Make scripts executable
        run: chmod +x scripts/sysinfo.sh

      - name: Run sysinfo.sh
        run: ./scripts/sysinfo.sh
